# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cFKb2wklIbJlcUwaq4Dyb1gYem4wy1hV
"""

def tashxis(belgi):
  if belgi=="istima":
    return"Paratsetamol iching"
  elif belgi=="katarakta":
    return"Deksametazon"
  elif belgi=="bosh og'rig'i":
    return"Trimol"
  elif belgi=="gripp":
    return"Taylolhot"
  else:
    return "shifokorga murojat qiling "
belgi=input("kasallik belgisini kiriting")
natija=tashxis(belgi)
print(natija)